id: P143DB3B5
initial_creation_type: input
source_metadata:
  title: Chöje Lingpa Series
  language: bo
  description: 'Texts by and about the treasure-revealer Chöjé Lingpa (chos rje gling
    pa, 1682–1720):'
  volume:
    d2e5161297d04700ae468d3f8abd0a08:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Longevity
    329c78061caf44bba2c211ba42212dc9:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Longevity
created_at: '2022-02-28T22:44:31.894242'
last_modified_at: '2022-02-28T22:44:31.894244'
statistics:
  total_words: 3456
  total_non_words: 496
quality:
  non_words_ratio: 0.14
